version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db-volume:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:4.9.4-php7.2
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./wp-content/wp-config.php:/var/www/html/wp-content/wp-config.php
       - ./wp-content:/var/www/html/wp-content

volumes:
    db-volume:
